version: '3'
services:
  web:
    container_name: random_word_api
    build: .
    restart: always
    ports:
      - '80:80'
    links:
      - db
    volumes:
      - .:/var/www/html
  db:
    container_name: rwa-mysql
    image: mysql
    ports:
      - '3309:3306'
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"

